[build]
buildCommand = "chmod +x mvnw && JAVA_HOME=/mise/installs/java/21.0.2 ./mvnw -B -DskipTests clean install -Pproduction"

[deploy]
startCommand = "JAVA_HOME=/mise/installs/java/21.0.2 java -jar target/*.jar"
